GIT/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GIT.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^error/([\w-]+)$', 'base.views.error'),

    url(r'^$', 'base.views.home'),
    url(r'^login$', 'base.views.login_procesar'),
    url(r'^logout$', 'base.views.logout_procesar'),

    url(r'^incidencia$', 'base.views.nueva_incidencia'),
    url(r'^incidencia/([\d]+)$', 'base.views.incidencia'),
    url(r'^cerrar$', 'base.views.cerrar'),

    url(r'^comentario/([\d]+)$', 'base.views.comentario'),

    url(r'^notificaciones$', 'base.views.notificaciones'),
    url(r'^notificaciones/([\d]+)$', 'base.views.ver_notificacion'),

    url(r'^estadisticas$', 'base.views.estadisticas'),

    url(r'^ayuda$', 'base.views.ayuda'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^perfil$', 'base.views.perfil'),
)

base/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

ESTADOS = (
        ('SO', 'Solicitada'),
        ('AC', 'Aceptada'),
        ('AS', 'Asignada'),
        ('CP', 'Cerrada prematuramente'),
        ('CTE', 'Cerrada con solución'),
        ('CTF', 'Cerrada sin solución')
    )

CATEGORIAS = (
        ('HW', 'Hardware'),
        ('CO', 'Comunicaciones'),
        ('SWB', 'Software básico'),
        ('SWA', 'Software de aplicaciones')
        )

class ElementoInventario(models.Model):
    nombre = models.CharField(max_length=40, default="")
    precio_compra = models.FloatField()
    fecha_compra = models.DateField(default=datetime.datetime.today)
    caracteristicas = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class Incidencia(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    prioridad = models.IntegerField(null=True, blank=True)
    categoria = models.CharField(max_length=3, choices=CATEGORIAS)
    estado = models.CharField(max_length=3, choices=ESTADOS, default='SO')
    inventario = models.ForeignKey(ElementoInventario, null=True, blank=True)

    fecha_apertura = models.DateField(default=datetime.date.today)
    fecha_cierre = models.DateField(null=True, blank=True)
    resuelta_exito = models.BooleanField(default=False)

    tecnico_asignado = models.ForeignKey(User, null=True, blank=True, related_name="tecnico_asignado")
    supervisor = models.ForeignKey(User, null=True, blank=True, related_name="supervisor")
    autor = models.ForeignKey(User, null=True, blank=True, related_name="autor")

class CambioEstado(models.Model):
    incidencia = models.ForeignKey(Incidencia)
    usuario = models.ForeignKey(User)
    fecha_cambio = models.DateField(default=datetime.datetime.today)
    estado_inicial = models.CharField(max_length=3, choices=ESTADOS, default='SO')
    estado_final = models.CharField(max_length=3, choices=ESTADOS, default='AC')
    nuevo = models.BooleanField(default=True)

class Comentario(models.Model):
    comentario = models.TextField()
    fecha = models.DateTimeField(default=timezone.now)
    incidencia = models.ForeignKey(Incidencia, null=True, blank=True)
    usuario = models.ForeignKey(User, null=True, blank=True)

@receiver(post_save, sender=Incidencia)
def desencadenar_cambios_estado(sender, instance, created, raw, using, update_fields, **kwargs):
    """
        Handler que registra frente a la base de datos los cambios de estado necesarios
        a medida que se van produciendo.
    """
    cambio_estado = CambioEstado(incidencia=instance,
                                 nuevo=True)
    if instance.estado == 'AC' and len(CambioEstado.objects.filter(incidencia=instance, estado_inicial='SO')) == 0:
        cambio_estado.usuario = instance.autor
    elif instance.estado == 'AS':
        cambio_estado.usuario = instance.supervisor
        cambio_estado.estado_inicial = 'AC'
        cambio_estado.estado_final = 'AS'
    elif instance.estado == 'CP':
        cambio_estado.usuario = instance.autor
        cambio_estado.estado_inicial = 'AS'
        cambio_estado.estado_final = 'CP'
    elif instance.estado.startswith('CT'):
        cambio_estado.usuario = instance.tecnico_asignado
        if len(CambioEstado.objects.filter(incidencia=instance, estado_final='CP')) > 0:
            cambio_estado.estado_inicial = 'CP'
        else:
            cambio_estado.estado_inicial = 'AS'
        if instance.estado == 'CTE':
            cambio_estado.estado_final = 'CTE'
        elif instance.estado == 'CTF':
            cambio_estado.estado_final = 'CTF'
        else:
            return
    else:
        return

    cambio_estado.save()

base/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import extras
from base.models import Incidencia, ElementoInventario, CambioEstado, Comentario, ESTADOS

ESTADOS_CON_EMPTY = [('', '---------')]
ESTADOS_CON_EMPTY.extend(list(ESTADOS))

class NuevaIncidencia(forms.ModelForm):
    class Meta:
        model = Incidencia
        fields = ['nombre', 'descripcion', 'fecha_apertura', 'categoria']
        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 3}),
            'fecha_apertura': extras.SelectDateWidget(attrs={'class': 'form-control fecha_apertura'}),
            'categoria': forms.Select(),
        }

class SupervisorIncidencia(forms.ModelForm):
    class Meta:
        model = Incidencia
        fields = ['prioridad', 'inventario', 'tecnico_asignado']

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['comentario']

class ListadoForm(forms.Form):
    tecnico_asignado = forms.ModelChoiceField(User.objects.filter(groups__name="tecnicos"), required=False)
    autor = forms.ModelChoiceField(User.objects.filter(groups__name="clientes"), required=False)
    estado = forms.ChoiceField(ESTADOS_CON_EMPTY, required=False)

base/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render, redirect

from django.contrib.auth.models import Group, User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from base.models import Incidencia, CambioEstado, Comentario
from base.forms import SupervisorIncidencia, NuevaIncidencia, ComentarioForm, ListadoForm

NUM_INCIDENCIAS_POR_PAGINA = 10


def get_notificaciones(usuario):
    grupos = usuario.groups.all()
    supervisores = Group.objects.get(name='supervisores')
    tecnicos = Group.objects.get(name='tecnicos')

    if supervisores in grupos:
        incidencias = Incidencia.objects.filter(supervisor=usuario)
        notificaciones = CambioEstado.objects.filter(estado_final__startswith="CT")
        notificaciones = notificaciones.filter(incidencia__in=incidencias).filter(nuevo=True)
    elif tecnicos in grupos:
        incidencias = Incidencia.objects.filter(tecnico_asignado=usuario)
        notificaciones = CambioEstado.objects.filter(estado_final="CP")
        notificaciones = notificaciones.filter(incidencia__in=incidencias).filter(nuevo=True)
    else:
        notificaciones = []
    return notificaciones

def error(request, tipo):
    """
        Muestra un mensaje de error en la pantalla
    """
    context = {}
    if tipo == 'login-inactivo':
        context['mensaje'] = 'El usuario está deshabilitado.'
    elif tipo == 'login-invalido':
        context['mensaje'] = 'El usuario no existe.'
    elif tipo.startswith('login'):
        context['mensaje'] = 'Ha habido un error en el login.'
    elif tipo == "incidencia-invalida":
        context['mensaje'] = 'La incidencia no existe.'
    elif tipo == "sin-permisos":
        context['mensaje'] = 'No tienes permisos.'
    elif tipo == "cerrar-invalido":
        context['mensaje'] = 'No puedes cerrar esta incidencia.'
    else:
        context['mensaje'] = 'Algo misterioso ha ocurrido.'
    return render(request, 'error.html', context)


def home(request):
    """
        Home de la página web, depende de si el usuario está autenticado o no
    """
    if request.user.is_authenticated():
        # Imprimir el listado de las incidencias
        grupos = request.user.groups.all()
        clientes = Group.objects.get(name='clientes')
        tecnicos = Group.objects.get(name='tecnicos')
        supervisores = Group.objects.get(name='supervisores')
        context = {'grupos': [g.name for g in grupos]}
        context['notificaciones_badge'] = len(get_notificaciones(request.user))

        if clientes in grupos:
            incidencias = Incidencia.objects.filter(autor=request.user).filter(estado__in=['AS', 'AC'])
        elif tecnicos in grupos:
            incidencias = Incidencia.objects.filter(tecnico_asignado=request.user).filter(estado__in=['AS', 'AC'])
        elif supervisores in grupos:
            # Formulario de filtrado para el supervisor
            incidencias = Incidencia.objects.all()
            if "tecnico_asignado" in request.GET and request.GET['tecnico_asignado']:
                incidencias = incidencias.filter(tecnico_asignado=request.GET['tecnico_asignado'])
            if "autor" in request.GET and request.GET['autor']:
                incidencias = incidencias.filter(autor=request.GET['autor'])
            if "estado" in request.GET and request.GET['estado']:
                incidencias = incidencias.filter(estado=request.GET['estado'])
            else:
                incidencias = incidencias.filter(estado__in=['AS', 'AC'])
            context['form'] = ListadoForm(request.GET)
        else:
            return redirect('/error/sin-permisos')

        # Paginar
        pagina = int(request.GET['pagina']) if 'pagina' in request.GET else 1
        paginator = Paginator(incidencias, NUM_INCIDENCIAS_POR_PAGINA)
        try:
            incidencias = paginator.page(pagina)
        except PageNotAnInteger:
            incidencias = paginator.page(1)
            pagina = 1
        except EmptyPage:
            incidencias = paginator.page(paginator.num_pages)
            pagina = paginator.num_pages
        context['paginas'] = range(1, paginator.num_pages + 1)
        context['pagina_actual'] = pagina
        context['incidencias'] = incidencias
        return render(request, 'listado.html', context)
    else:
        # Imprimir el login
        return render(request, 'login.html', {})


def login_procesar(request):
    """
        View para login llamado cuando se envía el formulario de login
    """
    if 'usuario' in request.POST and 'password' in request.POST:
        username = request.POST['usuario']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                return redirect('/error/login-inactivo')
        else:
            return redirect('/error/login-invalido')
    else:
        return redirect('/error/login')

def logout_procesar(request):
    """
        View para logout
    """
    logout(request)
    return redirect('/')

@login_required
def perfil(request):
    """
        Página para el perfil
    """
    grupos = [g.name for g in request.user.groups.all()]
    context = {'peticion': 'perfil', 'grupos': grupos}
    context['notificaciones_badge'] = len(get_notificaciones(request.user))
    context['usuario'] = request.user

    if request.method == 'GET':
        return render(request, 'perfil.html', context)
    else:
        # Procesar el cambio de los datos
        request.user.first_name = request.POST['nombre']
        request.user.last_name = request.POST['apellidos']
        request.user.email = request.POST['email']
        if len(request.POST['password-nuevo']) > 0 and request.user.check_password(request.POST['password-actual']):
            request.user.set_password(request.POST['password-nuevo'])
        request.user.save()
        request.POST = None
        return render(request, 'perfil.html', context)

@login_required
def ayuda(request):
    """
        Página para la ayuda
    """
    grupos = [g.name for g in request.user.groups.all()]
    context = {'peticion': 'ayuda', 'grupos': grupos}
    context['notificaciones_badge'] = len(get_notificaciones(request.user))

    return render(request, 'ayuda.html', context)

@login_required
def incidencia(request, id_incidencia):
    """
        View para mostrar las incidencias con el formulario para el supervisor
    """
    grupos = request.user.groups.all()
    supervisores = Group.objects.get(name='supervisores')
    context = {'grupos': [g.name for g in grupos]}
    context['notificaciones_badge'] = len(get_notificaciones(request.user))
    try:
        incidencia = Incidencia.objects.get(id=id_incidencia)
        context['incidencia'] = incidencia
        context['comentarios'] = Comentario.objects.filter(incidencia=incidencia)
    except Incidencia.DoesNotExist:
        return redirect('/error/incidencia-invalida')

    # Si el supervisor ha enviado el formulario para completar la incidencia
    if request.method == 'POST':
        # Un supervisor solo puede modificar incidencias que estén en estado AC
        if supervisores in grupos and incidencia.estado == 'AC':
            form = SupervisorIncidencia(request.POST, instance=incidencia)
            form.fields['tecnico_asignado'].queryset = User.objects.filter(groups__name="tecnicos")
            if form.is_valid():
                incidencia = form.save()
                incidencia.estado = 'AS'
                incidencia.supervisor = request.user
                incidencia.save()
                return redirect('/incidencia/' + str(id_incidencia))
            # Si algún campo del formulario del supervisor es inválido
            else:
                request.POST = None
                context['form'] = form

    context['form_comentario'] = ComentarioForm()
    # Mostrar la página de incidencia
    if 'form' not in context and incidencia.estado == 'AC':
        form = SupervisorIncidencia(instance=incidencia)
        form.fields['tecnico_asignado'].queryset = User.objects.filter(groups__name="tecnicos")
        context['form'] = form
    return render(request, 'resumen-incidencia.html', context)


@login_required
def cerrar(request):
    """
        View para cerrar incidencias ya sean prematuras, exitosas o fracasadas.
    """
    grupos = request.user.groups.all()
    context = {'grupos': [g.name for g in grupos]}
    clientes = Group.objects.get(name='clientes')
    tecnicos = Group.objects.get(name='tecnicos')

    # Si la petición es correcta
    if 'tipo' in request.GET and 'incidencia' in request.GET:
        id_incidencia = request.GET['incidencia']
        try:
            incidencia = Incidencia.objects.get(id=id_incidencia)
        # Si la incidencia es inválida
        except Incidencia.DoesNotExist:
            return redirect('/error/incidencia-invalida')

        if tecnicos in grupos and incidencia.tecnico_asignado == request.user:
            # Si el estado de la incidencia es consistente
            if incidencia.estado == 'AS' or incidencia.estado == 'CP':
                if 'exito' == request.GET['tipo']:
                    incidencia.estado = 'CTE'
                elif 'fracaso' == request.GET['tipo']:
                    incidencia.estado = 'CTF'
                else:
                    return redirect('/incidencia/' + str(incidencia.id))
            else:
                return redirect('/error/cerrar-invalido')
        elif clientes in grupos and incidencia.autor == request.user:
            if 'prematuro' == request.GET['tipo'] and incidencia.estado in ['AS', 'AC']:
                incidencia.estado = 'CP'
            else:
                return redirect('/error/cerrar-invalido')
        else:

base/templates/abrir-incidencia.html
{% extends "base.html" %}
{% block title %} Abrir nueva incidencia {% endblock %}
{% block head %}
    <style>
        .fecha_apertura{
            display: inline;
            width: 120px;
        }
    </style>
{% endblock %}
{% block navegacion %}
    {% include "navegacion.html" %}
{% endblock %}

{% block contenido %}
    <form action="./incidencia" method="post">
        {% include "formulario.html" %}
    </form>
{% endblock %}

base/templates/ayuda.html
{% extends "base.html" %}
{% block title %}Ayuda{% endblock %}
{% block navegacion %}
    {% include "navegacion.html" %}
{% endblock %}

{% block contenido %}
    <p>Por desarrollar</p>
{% endblock %}

base/templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>GIT | {% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/static/base.css">
        {% block head %}{% endblock %}
    </head>
    <body>
        {% block navegacion %}{% endblock %}

        <div class="container">
            {% block contenido %}{% endblock %}
            <div class="row">
                <div class="col-xs-12">
                    <footer>
                        <p>Sistema realizado por Oscar Gonzalez, Alejandro López, Miguel Sánchez y Stoyan Veselinov</p>
                    </footer>
                </div>
            </div>
        </div>
        <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

base/templates/error.html
{% extends "base.html" %}
{% block title %}Error{% endblock %}

{% block head %}
    <style>
        .jumbotron{
            margin-top: 10px;
        }
    </style>
{% endblock %}

{% block contenido %}
    <div class="jumbotron col-xs-12">
        <h1>Error</h1>
        <p>{{ mensaje }} </p>
        <p><a class="btn btn-primary btn-lg" href="/">Home</a></p>
    </div>
{% endblock %}

base/templates/formulario.html
{% load addclass %}
{% csrf_token %}
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {% if field.label == 'Fecha apertura' %}
            <div>
                {{ field }}
            </div>
        {% else %}
            {{ field|addclass:'form-control' }}
        {% endif %}
    </div>
{% endfor %}
<button type="submit" class="btn btn-primary">Enviar</button>

base/templates/listado.html
{% extends "base.html" %}
{% block title %} Listado {% endblock %}
{% block navegacion %}
    {% include "navegacion.html" %}
{% endblock %}
{% block head %}
    <style>
        form select.form-control{
            width: inherit;
            display:inline;
        }
        form label{
            width: 180px;
        }
    </style>
{% endblock %}

{% block contenido %}
    <h1>Listado de incidencias</h1>
    {% if "supervisores" in grupos %}
        <form method="get" action="/">
            {% include "formulario.html" %}
        </form>
    {% endif %}

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Fecha Apertura</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            {% for incidencia in incidencias %}
                <tr id="incidencia-{{ incidencia.id }}">
                    <td>{{ incidencia.id }}</td>
                    <td>{{ incidencia.nombre }}</td>
                    <td>{{ incidencia.fecha_apertura }}</td>
                    <td>{{ incidencia.get_estado_display }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <nav class="text-center">
        <ul class="pagination">
            {% for pagina in paginas %}
                <li {% if pagina == pagina_actual %}class="active"{% endif %}>
                    <a href="/?pagina={{ pagina }}">{{ pagina }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
{% endblock %}
{% block scripts %}
    <script>
        $("tr").click(function(e){
            var notificacion = $(e.target).parent().attr('id').substr(11);
            window.location.replace("/incidencia/" + notificacion);
        });
    </script>
{% endblock %}

base/templates/login.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>GIT</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/static/base.css">
        <style>
            html, body, .wrapper{
                height: 100%;
                overflow: hidden;
            }

            .wrapper{
                position: relative;
                background: #d6d6d6; /* Old browsers */
                background: -moz-radial-gradient(center, ellipse cover, #d6d6d6 0%, #3e4149 100%); /* FF3.6+ */
                background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,#d6d6d6), color-stop(100%,#3e4149)); /* Chrome,Safari4+ */
                background: -webkit-radial-gradient(center, ellipse cover, #d6d6d6 0%,#3e4149 100%); /* Chrome10+,Safari5.1+ */
                background: -o-radial-gradient(center, ellipse cover, #d6d6d6 0%,#3e4149 100%); /* Opera 12+ */
                background: -ms-radial-gradient(center, ellipse cover, #d6d6d6 0%,#3e4149 100%); /* IE10+ */
                background: radial-gradient(ellipse at center, #d6d6d6 0%,#3e4149 100%); /* W3C */
                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#d6d6d6', endColorstr='#3e4149',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
            }

            form{
                margin: 0 auto;
                width: 330px;
                border-radius: 5px;
                box-shadow: #555 0 0 10px;
                padding: 10px 15px;
                position: relative;
                top: 35%;
                z-index: 10;
                background: #eee;
            }

            .grupo{
                margin: 0 0 10px 0;
            }

            .grupo label{
                width: 90px;
            }

            .grupo input{
                width: 205px;
            }

            footer{
                position: absolute;
                left: 10px;
                bottom: -10px;
                color: #eee;
            }

            @media (max-height: 300px){
                form{
                    top: 20%;
                }
            }
        </style>
    </head>
    <body>
        <div class="wrapper">
            <form action="/login" method="post">
                {% csrf_token %}
                <div class="cuadro">
                    <div class="grupo">
                        <label class="" for="usuario">Usuario:</label>
                        <input class="" type="text" name="usuario" placeholder="Introduce tu nombre de usuario" autofocus>
                    </div>
                    <div class="grupo">
                        <label class="" for="password">Contraseña:</label>
                        <input class="" type="password" name="password" placeholder="Introduce tu contraseña">
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
            <footer>
                <p>Sistema realizado por Oscar Gonzalez, Alejandro López, Miguel Sánchez y Stoyan Veselinov</p>
            </footer>
        </div>
    </body>
</html>

base/templates/notificaciones.html
{% extends "base.html" %}
{% block title %} Notificaciones {% endblock %}
{% block navegacion %}
    {% include "navegacion.html" %}
{% endblock %}

{% block contenido %}
    <h1>Notificaciones</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Fecha Cambio</th>
                <th>Estado</th>
                {% if "tecnicos" in grupos %}
                    <th>Autor</th>
                {% elif "supervisores" in grupos %}
                    <th>Técnico asignado</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for notificacion in notificaciones %}
                <tr id="notificacion-{{ notificacion.id }}">
                    <td>{{ notificacion.incidencia.id }}</td>
                    <td>{{ notificacion.incidencia.nombre }}</td>
                    <td>{{ notificacion.fecha_cambio }}</td>
                    <td>{{ notificacion.get_estado_final_display }}</td>
                    <td>{{ notificacion.usuario }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block scripts %}
    <script>
        $("tr").click(function(e){
            var notificacion = $(e.target).parent().attr('id').substr(13);
            window.location.replace("/notificaciones/" + notificacion);
        });
    </script>
{% endblock %}

base/templates/resumen-incidencia.html
{% extends "base.html" %}
{% block title %}Incidencia A{% endblock %}
{% block navegacion %}
    {% include "navegacion.html" %}
{% endblock %}

{% block head %}
    <style>
        .comentario-form textarea{
            display: block;
            width: 100%;
        }
    </style>
{% endblock %}

{% block contenido %}
    <div class="resumen-incidencia">
        <h1>{{ incidencia.nombre }}</h1>
        <div class="col-md-4">
            <div class="dato">
                <h4>Número: </h4><span>{{ incidencia.id }}</span>
            </div>
            <div class="dato">
                <h4>Fecha Apertura: </h4><span>{{ incidencia.fecha_apertura }}</span>
            </div>
            <div class="dato">
                <h4>Autor: </h4><span>{{ incidencia.autor }}</span>
            </div>
            <div class="dato">
                <h4>Supervisor: </h4><span>{{ incidencia.supervisor|default:"--" }}</span>
            </div>
            <div class="dato">
                <h4>Estado: </h4><span>{{ incidencia.get_estado_display }}</span>
            </div>
            <div class="dato">
                <h4>Categoria: </h4><span>{{ incidencia.get_categoria_display }}</span>
            </div>
            {% if "supervisores" not in grupos or incidencia.estado != 'AC' %}
                <div class="dato">
                    <h4>Técnico Asignado: </h4><span>{{ incidencia.tecnico_asignado|default:"--" }}</span>
                </div>
                <div class="dato">
                    <h4>Prioridad: </h4><span>{{ incidencia.prioridad|default:"--" }}</span>
                </div>
                <div class="dato">
                    <h4>Inventario afectado: </h4><span>{{ incidencia.inventario|default:"--" }}</span>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="col-md-8">
        <h4>Descripcion:</h4>
        <div>
            {{ incidencia.descripcion }}
        </div>
    </div>

    <div class="clearfix"></div>
    <div class="comentarios">
        {% for comentario in comentarios %}
        <div class="panel panel-info">
            <div class="panel-heading">Por {{ comentario.usuario }} el {{ comentario.fecha }}</div>
            <div class="panel-body">
                {{ comentario.comentario }}
            </div>
        </div>
        {% endfor %}
    </div>
    {% if "supervisores" in grupos and incidencia.estado == 'AC' %}
        <form method="post" action="/incidencia/{{ incidencia.id }}">
            {% include "formulario.html" %}
        </form>

    {% endif %}
    {% if "tecnicos" in grupos %}
        <form method="post" action="/comentario/{{ incidencia.id }}" class="comentario-form">
            {% csrf_token %}
            {{ form_comentario }}
            <button style="margin-top: 5px" type="submit" class="btn btn-primary">Enviar comentario</button>
        </form>
        {% if incidencia.estado == "AS" or incidencia.estado == "CP" %}
            <a class="btn btn-primary" href="/cerrar?tipo=exito&incidencia={{ incidencia.id }}" style="margin-top: 20px;">Cerrar con éxito</a>
            <a class="btn btn-danger" href="/cerrar?tipo=fracaso&incidencia={{ incidencia.id }}" style="margin-top: 20px;">Cerrar con fracaso</a>
        {% endif %}
    {% endif %}
    {% if "clientes" in grupos %}
        {% if incidencia.estado == "AS" or incidencia.estado == "AC" %}
            <a class="btn btn-primary" href="/cerrar?tipo=prematuro&incidencia={{ incidencia.id }}" style="margin-top: 20px;">Cerrar</a>
        {% endif %}
    {% endif %}

{% endblock %}